// Package dconf is the policy manager for dconf entry types.
//
// The manager will create additional dconf databases: system-db:<username> and system-db:machine.
// Values specified in the GPO will be appended to those databases, according to their configuration.
// Dconf applies the values from bottom to top and stops checking values for a certain key at the
// moment it finds a lock.
// Default values specified by the policy will be added to the profile database, along with locks to
// their correspondent keys, in order to enforce the requested values.
//
// The manager will parse the values and try to fix some formatting problems, but if something goes
// wrong when applying the profile or updating dconf, an error is returned.
// However, ADSys will not check for the correctness of the values being assigned and it's up to the
// admin to ensure that the requested value is assignable to the key it is being assigned to.
//
// Notes or common keys between user and machine:
//
// 1. Machine is not configured (no value, no lock) -> upper layers will be taken into account, which can be the user
// one or user default value.
//
// 2. Machine is configured (value, and lock) -> the lock will "stick" our desired value and enforce it.
//
// 3. Machine configuration is set to deleted, conveying "I want the default value from the system" (no value, and lock)
// -> the lock will "stick" the desired value to the layer of current value of Machine. As machine doesn’t have any
// value and is the lowest in the stack (the first one to be processed), this will thus enforce the default system
// configuration for that setting.
package dconf

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/godbus/dbus/v5"
	"github.com/leonelquinteros/gotext"
	"github.com/ubuntu/adsys/internal/consts"
	log "github.com/ubuntu/adsys/internal/grpc/logstreamer"
	"github.com/ubuntu/adsys/internal/policies/entry"
	"github.com/ubuntu/adsys/internal/smbsafe"
	"github.com/ubuntu/decorate"
)

const (
	// defaultUserDB is the write database generated profiles fall back to when
	// no system profile provides one.
	defaultUserDB = "user-db:user"

	// profileDataDirsEnv overrides the directories searched for system dconf
	// profiles. It is only honored by test binaries, which must not depend on
	// the dconf profiles installed on the machine running them.
	profileDataDirsEnv = "ADSYS_TESTS_DCONF_PROFILE_DATA_DIRS"

	// generatedProfileMarker starts the header of the profiles we seeded from a
	// system profile. It is what tells us, on the next refresh, that the
	// sources a profile carries are borrowed ones we must bring up to date,
	// rather than an administrator's own configuration.
	generatedProfileMarker = "# Generated by adsys"
)

// defaultProfileDataDirs are the data directories dconf looks system profiles
// up in when XDG_DATA_DIRS is not set, in lookup order.
var defaultProfileDataDirs = []string{"/usr/local/share", "/usr/share"}

// Manager prevents running multiple dconf update process in parallel while parsing policy in ApplyPolicy.
type Manager struct {
	// dconfMu prevents applying dconf policies for users and machine in parallel.
	// Applying the policy for the machine can only be done if we are not applying it for any user.
	dconfMu sync.RWMutex
	// dconfUpdateMu prevents running multiple dconf update processes in parallel.
	dconfUpdateMu sync.Mutex

	dconfDir        string
	profileDataDirs []string
	dconfUpdater    func(dbDir string) ([]byte, error)
}

// NewWithDconfDir creates a manager with a specific dconf directory.
func NewWithDconfDir(dir string) *Manager {
	return newWithDconfDirAndProfileDataDirs(dir, nil)
}

func newWithDconfDirAndProfileDataDirs(dir string, profileDataDirs []string) *Manager {
	return &Manager{dconfDir: dir, profileDataDirs: profileDataDirs}
}

// profileSearchDirs returns the directories to look system dconf profiles up
// in, in lookup order.
//
// The system defaults are always searched, even when XDG_DATA_DIRS is set: the
// profiles we generate are consumed by other services — GDM for instance —
// whose data directories are not necessarily the ones the daemon runs with.
func (m *Manager) profileSearchDirs() []string {
	if m.profileDataDirs != nil {
		return m.profileDataDirs
	}

	if testing.Testing() {
		if dirs, isSet := os.LookupEnv(profileDataDirsEnv); isSet {
			return filepath.SplitList(dirs)
		}
	}

	var dataDirs []string
	seen := make(map[string]struct{})
	for _, dataDir := range append(filepath.SplitList(os.Getenv("XDG_DATA_DIRS")), defaultProfileDataDirs...) {
		if dataDir == "" {
			continue
		}
		// XDG_DATA_DIRS entries are commonly written with a trailing separator,
		// which must not make us search the same directory twice.
		dataDir = filepath.Clean(dataDir)
		if _, alreadySeen := seen[dataDir]; alreadySeen {
			continue
		}
		seen[dataDir] = struct{}{}
		dataDirs = append(dataDirs, dataDir)
	}

	return dataDirs
}

// ApplyPolicy generates a dconf computer or user policy based on a list of entries.
func (m *Manager) ApplyPolicy(ctx context.Context, objectName string, isComputer bool, entries []entry.Entry) (err error) {
	defer decorate.OnError(&err, gotext.Get("can't apply dconf policy to %s", objectName))

	dconfDir := m.dconfDir
	if dconfDir == "" {
		dconfDir = consts.DefaultDconfDir
	}

	// Since the user dconf configuration is reliant on the machine dconf configuration, we can't
	// apply them in parallel. The strategy works as follows:
	// 	- Any number of users can have the policy applied in parallel;
	//	- Machine policy can't be applied if there are any user policies being applied;
	// dconfMu is used to prevent that.
	if isComputer {
		m.dconfMu.Lock()
		defer m.dconfMu.Unlock()
	} else {
		m.dconfMu.RLock()
		defer m.dconfMu.RUnlock()
	}

	log.Debugf(ctx, "Applying dconf policy to %s", objectName)

	if isComputer {
		objectName = "machine"
	}

	// The object name is what we name the databases and profiles we write
	// after, and what we look the system profile up as: refuse any name that
	// would let it designate a file outside of the directories we own.
	if filepath.Base(objectName) != objectName || objectName == "." || objectName == ".." {
		return errors.New(gotext.Get("invalid object name %q: it must not designate a path", objectName))
	}

	profilesPath := filepath.Join(dconfDir, "profile")
	dbsPath := filepath.Join(dconfDir, "db")
	dbPath := filepath.Join(dbsPath, objectName+".d")

	if !isComputer {
		if _, err := os.Stat(filepath.Join(dbsPath, "machine.d", "locks", "adsys")); err != nil {
			return errors.New(gotext.Get("machine dconf database is required before generating a policy for an user. This one returns: %v", err))
		}
	}

	// Create profiles for users only
	if !isComputer {
		//nolint:gosec // G301 - Profile must be readable by everyone
		if err := os.MkdirAll(profilesPath, 0755); err != nil {
			return err
		}
		if err := writeProfile(ctx, objectName, profilesPath, m.profileSearchDirs()); err != nil {
			return err
		}
	}

	// Generate defaults and locks content from policy
	dataWithGroups := make(map[string][]string)
	var locks []string
	var errMsgs []string
	for _, e := range entries {
		log.Debugf(ctx, "Analyzing entry %+v", e)

		if !e.Disabled {
			section := filepath.Dir(e.Key)

			// normalize common user error cases and check gsettings schema signature match.
			e.Value = normalizeValue(e.Meta, e.Value)
			if err := checkSignature(e.Meta, e.Value); err != nil {
				errMsgs = append(errMsgs, gotext.Get("- error on %s: %v", e.Key, err))
				continue
			}

			l := fmt.Sprintf("%s=%s", filepath.Base(e.Key), e.Value)
			dataWithGroups[section] = append(dataWithGroups[section], l)
		}
		locks = append(locks, "/"+e.Key)
	}

	// Stop on any error
	if errMsgs != nil {
		return errors.New(strings.Join(errMsgs, "\n"))
	}

	// Prepare file contents
	// Order sections to have a reliable output
	var data []string
	sections := make([]string, 0, len(dataWithGroups))
	for s := range dataWithGroups {
		sections = append(sections, s)
	}
	sort.Strings(sections)
	for _, s := range sections {
		data = append(data, fmt.Sprintf("[%s]", s))
		data = append(data, dataWithGroups[s]...)
	}

	var needsRefresh bool

	// Commit on disk
	//nolint:gosec // G301 - Locks must be readable by everyone
	if err := os.MkdirAll(filepath.Join(dbPath, "locks"), 0755); err != nil {
		return err
	}

	defaultPath := filepath.Join(dbPath, "adsys")
	changed, err := writeIfChanged(defaultPath, strings.Join(data, "\n")+"\n")
	if err != nil {
		return err
	}
	needsRefresh = needsRefresh || changed

	locksPath := filepath.Join(dbPath, "locks", "adsys")
	changed, err = writeIfChanged(locksPath, strings.Join(locks, "\n")+"\n")
	if err != nil {
		return err
	}
	needsRefresh = needsRefresh || changed

	// update if any profile changed, or if any compiled db is missing
	managedDBs := []string{filepath.Join(dbsPath, "machine")}
	if !isComputer {
		managedDBs = append(managedDBs, filepath.Join(dbsPath, objectName))
	}
	for _, dbPath := range managedDBs {
		needsRefresh = needsRefresh || dconfNeedsUpdate(dbPath)
	}
	if !needsRefresh {
		return nil
	}

	// request an update now that we released the read lock
	// we will call update multiple times.
	smbsafe.WaitExec()
	m.dconfUpdateMu.Lock()
	// Snapshot current databases so same-tick compiles are still detected.
	databaseSnapshots := make([]dconfDatabaseSnapshot, len(managedDBs))
	for i, dbPath := range managedDBs {
		databaseSnapshots[i] = snapshotDconfDatabase(dbPath)
	}
	out, errExec := m.updateDconfDB(dbsPath)
	m.dconfUpdateMu.Unlock()
	smbsafe.DoneExec()
	if errExec != nil {
		updateErr := dconfUpdateError(out, errExec)

		var exitErr *exec.ExitError
		if !errors.As(errExec, &exitErr) {
			return updateErr
		}

		var staleDBs []string
		for i, dbPath := range managedDBs {
			if !dconfDatabaseWasRecompiled(dbPath, databaseSnapshots[i]) && !dconfDatabaseIsUpToDate(dbPath) {
				staleDBs = append(staleDBs, filepath.Base(dbPath))
			}
		}
		if len(staleDBs) > 0 {
			return fmt.Errorf("%w: %s", updateErr,
				gotext.Get("ADSys-managed dconf database(s) are missing or stale: %s", strings.Join(staleDBs, ", ")))
		}

		log.Warning(ctx, gotext.Get("dconf update failed, but ADSys-managed databases were compiled or are up to date (output: %q; error: %v)",
			string(out), errExec))
	}

	return nil
}

func (m *Manager) updateDconfDB(dbDir string) ([]byte, error) {
	if m.dconfUpdater != nil {
		return m.dconfUpdater(dbDir)
	}

	// #nosec G204 - dbDir is controlled by the manager and is not user input.
	return exec.Command("dconf", "update", dbDir).CombinedOutput()
}

func dconfUpdateError(output []byte, err error) error {
	return fmt.Errorf("%s: %w", gotext.Get("dconf update failed (output: %q)", string(output)), err)
}

// writeIfChanged will only write to path if content is different from current content.
func writeIfChanged(path string, content string) (done bool, err error) {
	defer decorate.OnError(&err, gotext.Get("can't save %s", path))

	if oldContent, err := os.ReadFile(path); err == nil && string(oldContent) == content {
		return false, nil
	}

	//nolint:gosec // G306 - This asset needs to be world-readable.
	if err := os.WriteFile(path+".new", []byte(content), 0644); err != nil {
		return false, err
	}
	if err := os.Rename(path+".new", path); err != nil {
		return false, err
	}

	return true, nil
}

// writeProfile creates or updates a dconf profile file. Profiles generated by
// ADSys use the matching system profile as their base when available and carry
// an ownership marker; administrator-managed profiles are left intact apart
// from appending our databases.
//
// Our databases are appended last, below the sources we seeded the profile
// with, even though dconf gives priority to the sources declared first. That
// still enforces the policy: every key a GPO configures is locked, and a lock
// confines the lookup to the database holding it and the ones declared after
// it, so the sources above ours never answer for a key we manage. The keys no
// GPO configures are the ones left unlocked, and they keep resolving to the
// defaults the seeded sources provide, which is the point of preserving them.
func writeProfile(ctx context.Context, user, profilesPath string, dataDirs []string) (err error) {
	defer decorate.OnError(&err, gotext.Get("can't update user profile %s", profilesPath))

	profilePath := filepath.Join(profilesPath, user)
	log.Debugf(ctx, "Update user profile %s", profilePath)

	adsysMachineDB := "system-db:machine"
	adsysUserDB := fmt.Sprintf("system-db:%s", user)

	// Read existing content, if any.
	existing, err := os.ReadFile(profilePath)
	profileExists := err == nil
	if err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		existing = nil
	}

	// The profiles we own are seeded from the system profile they shadow, so
	// that the sources it declares — the GDM greeter defaults for instance —
	// are not dropped. Profiles set up by the administrator are left untouched
	// and only get our databases appended.
	base, header := existing, ""
	if !profileExists || isGeneratedProfile(existing, adsysUserDB, adsysMachineDB) {
		systemProfile, systemProfilePath, err := readSystemProfile(user, dataDirs)
		if err != nil {
			return err
		}
		// A blank system profile declares no source to preserve, and using it
		// as is would drop the write database from the generated profile.
		base = []byte(defaultUserDB)
		header = generatedProfileMarker + " and refreshed with the policy.\n" +
			"# Remove this header to manage this profile yourself."
		if len(bytes.TrimSpace(systemProfile)) > 0 {
			base = systemProfile
			// Borrowed sources go stale when the package shipping them changes
			// its profile, so record where they came from for clarity.
			header = fmt.Sprintf("%s from %s, and refreshed with the policy.\n"+
				"# Remove this header to manage this profile yourself.", generatedProfileMarker, systemProfilePath)
		}
	}

	// Read file to insert them at the end, removing duplicates
	var out []string
	if header != "" {
		out = append(out, header)
	}
	for _, d := range bytes.Split(bytes.TrimSpace(base), []byte("\n")) {
		// Add current line if it’s not an adsys one
		if string(d) == adsysMachineDB || string(d) == adsysUserDB ||
			strings.HasPrefix(strings.TrimSpace(string(d)), generatedProfileMarker) {
			continue
		}
		out = append(out, string(d))
	}
	out = append(out, adsysUserDB, adsysMachineDB)

	newContent := []byte(strings.Join(out, "\n"))

	// Is file already up to date?
	if profileExists && bytes.Equal(existing, newContent) {
		return nil
	}

	// Otherwise, update the file.
	//nolint:gosec // G306 - This asset needs to be world-readable.
	if err := os.WriteFile(profilePath+".adsys.new", newContent, 0644); err != nil {
		return err
	}
	if err := os.Rename(profilePath+".adsys.new", profilePath); err != nil {
		return err
	}
	return nil
}

// isGeneratedProfile reports whether content is a profile ADSys wrote rather
// than one an administrator maintains.
//
// Generated profiles carry a header, including when no system profile was
// available to seed them from. When a system profile was copied, the header
// records its path so a change to that profile — GDM moving its greeter
// defaults to another path, say — is picked up instead of being hidden by our
// stale copy for good.
//
// Older releases generated profiles without a header. Recognize their
// fallback profile so it can be migrated to the marked format. A blank profile
// carries no intent either, and is treated as generated.
func isGeneratedProfile(content []byte, adsysUserDB, adsysMachineDB string) bool {
	trimmed := string(bytes.TrimSpace(content))
	if trimmed == "" || trimmed == strings.Join([]string{defaultUserDB, adsysUserDB, adsysMachineDB}, "\n") {
		return true
	}

	for _, line := range strings.Split(trimmed, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), generatedProfileMarker) {
			return true
		}
	}
	return false
}

// readSystemProfile returns the content of the first profile named user found
// in dataDirs, along with the path it was read from. An empty path means no
// system profile shadows this object.
func readSystemProfile(user string, dataDirs []string) ([]byte, string, error) {
	for _, dataDir := range dataDirs {
		if dataDir == "" {
			continue
		}
		profilePath := filepath.Join(dataDir, "dconf", "profile", user)
		content, err := os.ReadFile(profilePath)
		if err == nil {
			return content, profilePath, nil
		}
		if !errors.Is(err, fs.ErrNotExist) {
			return nil, "", fmt.Errorf("%s: %w", gotext.Get("can't read system dconf profile %s", profilePath), err)
		}
	}
	return nil, "", nil
}

// dconfNeedsUpdate will notify if we need to run dconf update for that binary database.
// For now, it only checks its existence.
func dconfNeedsUpdate(path string) bool {
	if _, err := os.Stat(path); errors.Is(err, fs.ErrNotExist) {
		return true
	}

	return false
}

// dconfDatabaseIsUpToDate reports whether the compiled database is newer than
// the keyfile directory and the keyfiles dconf update compiles from it.
func dconfDatabaseIsUpToDate(path string) bool {
	database, err := os.Stat(path)
	if err != nil || !database.Mode().IsRegular() {
		return false
	}

	databaseTime := database.ModTime()
	keyfilesDir := path + ".d"
	dirInfo, err := os.Stat(keyfilesDir)
	if err != nil || !dirInfo.IsDir() || !databaseTime.After(dirInfo.ModTime()) {
		return false
	}

	keyfiles, err := os.ReadDir(keyfilesDir)
	if err != nil {
		return false
	}
	for _, keyfile := range keyfiles {
		keyfilePath := filepath.Join(keyfilesDir, keyfile.Name())
		if keyfile.Name() == "locks" {
			if !dconfLocksAreUpToDate(databaseTime, keyfilePath) {
				return false
			}
			continue
		}

		info, err := os.Stat(keyfilePath)
		if err != nil {
			return false
		}
		if !info.IsDir() && !databaseTime.After(info.ModTime()) {
			return false
		}
	}

	return true
}

type dconfDatabaseSnapshot struct {
	known bool
	info  os.FileInfo
}

func snapshotDconfDatabase(path string) dconfDatabaseSnapshot {
	info, err := os.Stat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return dconfDatabaseSnapshot{known: true}
	}
	if err != nil {
		return dconfDatabaseSnapshot{}
	}

	return dconfDatabaseSnapshot{known: true, info: info}
}

func dconfDatabaseWasRecompiled(path string, before dconfDatabaseSnapshot) bool {
	if !before.known {
		return false
	}

	info, err := os.Stat(path)
	if err != nil || !info.Mode().IsRegular() {
		return false
	}

	return before.info == nil || !os.SameFile(before.info, info) || !info.ModTime().Equal(before.info.ModTime())
}

func dconfLocksAreUpToDate(databaseTime time.Time, locksDir string) bool {
	dirInfo, err := os.Stat(locksDir)
	if errors.Is(err, fs.ErrNotExist) {
		return true
	}
	if err != nil || !dirInfo.IsDir() || !databaseTime.After(dirInfo.ModTime()) {
		return false
	}

	lockFiles, err := os.ReadDir(locksDir)
	if err != nil {
		return false
	}
	for _, lockFile := range lockFiles {
		info, err := os.Stat(filepath.Join(locksDir, lockFile.Name()))
		if err != nil || info.IsDir() || !databaseTime.After(info.ModTime()) {
			return false
		}
	}

	return true
}

// normalizeValue simplify user entry by handling common mistakes on key types.
func normalizeValue(keyType, value string) string {
	value = strings.TrimSpace(value)
	switch keyType {
	case "s":
		return quoteValue(value)
	case "b":
		return normalizeBoolean(value)
	case "i":
		return strings.ReplaceAll(strings.ReplaceAll(value, `"`, ""), "'", "")
	case "as":
		return quoteASVariant(value)
	case "ai":
		return normalizeAIVariant(value)
	}

	return value
}

// quoteValue ensures the string starts and ends with ' in s.
// We will escape each non leading character in s.
func quoteValue(s string) string {
	// quote automatically single quote
	switch s {
	case "'":
		s = `'''`
	case `\'`:
		s = `'\''`
	}

	s = strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(s), "'"), "'")
	return fmt.Sprintf("'%s'", strings.Join(splitOnNonEscaped(s, "'"), `\'`))
}

// normalizeBoolean will try to convert any value to false/true to be compatible with dconf.
// The following is accepted, is case insensitive and spaces are trimmed:
// y|yes|n|no
// true|false
// on|On|ON|off.
func normalizeBoolean(v string) string {
	lv := strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(strings.ToLower(v)), `"`, ""), "'", "")
	switch lv {
	case "y", "yes", "true", "on":
		return "true"
	case "n", "no", "false", "off":
		return "false"
	}
	return v
}

// quoteASVariant returns a variant array of string properly quoted and separated.
func quoteASVariant(v string) string {
	v = strings.TrimRight(strings.TrimLeft(v, " ["), " ]")

	// Remove any empty \n elements
	var elems []string
	for _, e := range strings.Split(v, "\n") {
		if strings.TrimSpace(e) == "" {
			continue
		}
		elems = append(elems, e)
	}
	v = strings.Join(elems, ",")

	// Quoted string case
	if strings.HasPrefix(v, "'") && strings.HasSuffix(v, "'") {
		// Remove leading/trailing quote and split on "','" (with optional spaces)
		v = strings.Trim(v, "'")
		re := regexp.MustCompile(`'\s*,\s*'`)
		t := re.Split(v, -1)

		var r []string
		for _, e := range t {
			r = append(r, quoteValue(e))
		}
		return fmt.Sprintf("[%s]", strings.Join(r, ", "))
	}

	// Unquoted string
	// Must split on "," but not on "\,"
	// Negative look behind is not supported in Go, so workaround by rejoining previous escaped element
	// https://github.com/google/re2/wiki/Syntax
	// Regex: `\s*(?<!\\),\s*`
	var r []string
	for _, e := range splitOnNonEscaped(v, ",") {
		e = fmt.Sprintf("'%s'", strings.TrimSpace(e))
		r = append(r, quoteValue(e))
	}

	return fmt.Sprintf("[%s]", strings.Join(r, ", "))
}

// normalizeAIVariant returns a variant array of int with proper separator.
func normalizeAIVariant(v string) string {
	v = strings.TrimRight(strings.TrimLeft(v, " ["), " ]")

	// Remove any empty \n elements
	var elems []string

	for _, e := range strings.Split(v, "\n") {
		if strings.TrimSpace(e) == "" {
			continue
		}
		elems = append(elems, e)
	}

	// normalize separator spaces
	v = strings.Join(elems, ",")
	v = strings.ReplaceAll(strings.ReplaceAll(v, " ", ""), ",", ", ")

	return fmt.Sprintf("[%s]", v)
}

// splitOnNonEscaped splits v by sep, only if sep is not escaped.
func splitOnNonEscaped(v, sep string) []string {
	t := strings.Split(v, sep)
	// rebuild the slice, rejoining "\,"
	var tokens []string
	for i, e := range t {
		if i == 0 {
			tokens = append(tokens, e)
			continue
		}
		// If the previous element was escaped (counting the number of \), merge it.
		if strings.HasSuffix(t[i-1], `\`) && ((len(t[i-1])-len(strings.TrimRight(t[i-1], `\`)))%2 == 1) {
			tokens[len(tokens)-1] += sep + e
			continue
		}
		tokens = append(tokens, e)
	}
	return tokens
}

// checkSignature returns an error if the value doesn't match the expected variant signature.
func checkSignature(meta, value string) (err error) {
	defer decorate.OnError(&err, gotext.Get("error while checking signature"))

	if meta == "" {
		return errors.New(gotext.Get("empty signature for %v", meta))
	}

	sig, err := dbus.ParseSignature(meta)
	if err != nil {
		return errors.New(gotext.Get("%s is not a valid gsettings signature: %v", meta, err))
	}
	_, err = dbus.ParseVariant(value, sig)
	if err != nil {
		return errors.New(gotext.Get("can't parse %q as %q: %v", value, meta, err))
	}

	return nil
}
