#!/bin/bash

set -eu

function releaseDockerExists() {
    local codename="${1}"
    curl "https://registry.hub.docker.com/api/content/v1/repositories/public/library/ubuntu/tags?page=-25&page_size=-1" 2>/dev/null | jq -r '.results[].name' | grep codename
}


