#!/bin/sh

# Only execute adsysctl on login for AD users

if [ -z "${PAM_USER}" ]; then
        echo "E: PAM_USER is not set. This script must be executed from pam_exec. Exiting!"
        exit 1
fi

[ -z "${KRB5CCNAME}" ] && exit 0

CCNAME=${KRB5CCNAME#FILE:}
adsysctl policy update ${PAM_USER} ${CCNAME} 2>&1